language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 3.0

script:
  - dotnet restore
  - dotnet build -c Release
  - dotnet test  /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../coverage/opencover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -f "coverage/opencover.xml"

branches:
  only:
    - master
    - development

notifications:
  slack: paramdigma:FtUcdwSDOynOHw2M479kXHxs
