language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 3.0

script:
  - dotnet restore
  - dotnet build -c Release
  - dotnet test  /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=../coverage/cobertura.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -f "coverage/cobertura.xml"

branches:
  only:
    - master
    - development
