name: Deploy docs

on:
  push:
    branches:
      - master
  
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Docs build & deploy
    steps:
      - uses: actions/checkout@v1
        name: Checkout 🛎
      - uses: nikeee/docfx-action@master
        name: Build Docs 📚
        with:
          args: docfx_project/docfx.json
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
 