name: Greet first-time contributors

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'This is your first issue! Thanks for taking the time to do this!!'
        pr-message: 'This is your first PR! Thanks for making Paramdigma.Core a little better!'
